// Generated by gencpp from file hexapod_training/QMatrix.msg
// DO NOT EDIT!


#ifndef HEXAPOD_TRAINING_MESSAGE_QMATRIX_H
#define HEXAPOD_TRAINING_MESSAGE_QMATRIX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hexapod_training/QMatrixElement.h>

namespace hexapod_training
{
template <class ContainerAllocator>
struct QMatrix_
{
  typedef QMatrix_<ContainerAllocator> Type;

  QMatrix_()
    : elements()  {
    }
  QMatrix_(const ContainerAllocator& _alloc)
    : elements(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::hexapod_training::QMatrixElement_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hexapod_training::QMatrixElement_<ContainerAllocator> >> _elements_type;
  _elements_type elements;





  typedef boost::shared_ptr< ::hexapod_training::QMatrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapod_training::QMatrix_<ContainerAllocator> const> ConstPtr;

}; // struct QMatrix_

typedef ::hexapod_training::QMatrix_<std::allocator<void> > QMatrix;

typedef boost::shared_ptr< ::hexapod_training::QMatrix > QMatrixPtr;
typedef boost::shared_ptr< ::hexapod_training::QMatrix const> QMatrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapod_training::QMatrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapod_training::QMatrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hexapod_training::QMatrix_<ContainerAllocator1> & lhs, const ::hexapod_training::QMatrix_<ContainerAllocator2> & rhs)
{
  return lhs.elements == rhs.elements;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hexapod_training::QMatrix_<ContainerAllocator1> & lhs, const ::hexapod_training::QMatrix_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hexapod_training

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hexapod_training::QMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapod_training::QMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_training::QMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_training::QMatrix_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_training::QMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_training::QMatrix_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapod_training::QMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb7bde857788bc279933d9d650b6350";
  }

  static const char* value(const ::hexapod_training::QMatrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb7bde857788bc2ULL;
  static const uint64_t static_value2 = 0x79933d9d650b6350ULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapod_training::QMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapod_training/QMatrix";
  }

  static const char* value(const ::hexapod_training::QMatrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapod_training::QMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#QMatrix.msg\n"
"hexapod_training/QMatrixElement[] elements\n"
"\n"
"================================================================================\n"
"MSG: hexapod_training/QMatrixElement\n"
"# QMatrixElement.msg\n"
"hexapod_training/StateActionPair pair\n"
"std_msgs/Float64 reward\n"
"\n"
"================================================================================\n"
"MSG: hexapod_training/StateActionPair\n"
"# StateActionPair.msg\n"
"string state\n"
"int32 action\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::hexapod_training::QMatrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapod_training::QMatrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QMatrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapod_training::QMatrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapod_training::QMatrix_<ContainerAllocator>& v)
  {
    s << indent << "elements[]" << std::endl;
    for (size_t i = 0; i < v.elements.size(); ++i)
    {
      s << indent << "  elements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hexapod_training::QMatrixElement_<ContainerAllocator> >::stream(s, indent + "    ", v.elements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPOD_TRAINING_MESSAGE_QMATRIX_H
