// Generated by gencpp from file hexapod_training/StateActionPair.msg
// DO NOT EDIT!


#ifndef HEXAPOD_TRAINING_MESSAGE_STATEACTIONPAIR_H
#define HEXAPOD_TRAINING_MESSAGE_STATEACTIONPAIR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hexapod_training
{
template <class ContainerAllocator>
struct StateActionPair_
{
  typedef StateActionPair_<ContainerAllocator> Type;

  StateActionPair_()
    : state()
    , action(0)  {
    }
  StateActionPair_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , action(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef int32_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::hexapod_training::StateActionPair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapod_training::StateActionPair_<ContainerAllocator> const> ConstPtr;

}; // struct StateActionPair_

typedef ::hexapod_training::StateActionPair_<std::allocator<void> > StateActionPair;

typedef boost::shared_ptr< ::hexapod_training::StateActionPair > StateActionPairPtr;
typedef boost::shared_ptr< ::hexapod_training::StateActionPair const> StateActionPairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapod_training::StateActionPair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapod_training::StateActionPair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hexapod_training::StateActionPair_<ContainerAllocator1> & lhs, const ::hexapod_training::StateActionPair_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hexapod_training::StateActionPair_<ContainerAllocator1> & lhs, const ::hexapod_training::StateActionPair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hexapod_training

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hexapod_training::StateActionPair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapod_training::StateActionPair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_training::StateActionPair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_training::StateActionPair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_training::StateActionPair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_training::StateActionPair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapod_training::StateActionPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea8f4a97a7ca851b7f7f92f5d00b7f93";
  }

  static const char* value(const ::hexapod_training::StateActionPair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea8f4a97a7ca851bULL;
  static const uint64_t static_value2 = 0x7f7f92f5d00b7f93ULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapod_training::StateActionPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapod_training/StateActionPair";
  }

  static const char* value(const ::hexapod_training::StateActionPair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapod_training::StateActionPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StateActionPair.msg\n"
"string state\n"
"int32 action\n"
;
  }

  static const char* value(const ::hexapod_training::StateActionPair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapod_training::StateActionPair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateActionPair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapod_training::StateActionPair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapod_training::StateActionPair_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPOD_TRAINING_MESSAGE_STATEACTIONPAIR_H
